export const HANDLE_INPUT_CHANGE = 'handle_input_change'
export const ADD_DATA = 'add_data'
export const UPDATE_DATA = 'update_data'
export const SET_INPUT_MESSAGE = 'set_input_message'
export const DELETE_DATA = 'delete_data'
export const SELECT_ROW = 'select_row'
